# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45312fb26a6072c8187b9af48c7d7bbaa7d5be4680bda1f9310a40a8b8d10958e4be479d627a1fd39ef3d93b933761bf1a015df5ca656b596e6a90d95a350377

test:
  secret_key_base: a19a86d8dd1b4c585a09826d7a9933de163b6c25655555ff46e37c2d1f823838d851e869a67a534dda669d183b0212f437eadc77f2467532dbff43f5d1005b92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
